export const CONTINENTS = [
  {
    id: "africa",
    name: "Africa",
    place: "Continent",
    lat: 1.0,
    lng: 20.0,
    emoji: "🌍",
    color: "#e8a838",
    kind: "continent",
    story:
      "Africa is a huge warm continent with deserts, jungles, tall mountains, and amazing animals like lions, elephants, and giraffes.",
    wow: "It is so big that you could fit the USA, China, India, and lots more countries inside it!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Africa-continent-outline.jpg/960px-Africa-continent-outline.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/a/a4/Africa1910s.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/African_continent-ar.png/960px-African_continent-ar.png"
    ],
    video: "KcNVNsvyFfA",
  },
  {
    id: "antarctica",
    name: "Antarctica",
    place: "Continent",
    lat: -80.0,
    lng: 0.0,
    emoji: "🐧",
    color: "#c5e4f3",
    kind: "continent",
    story:
      "Antarctica is the coldest continent — a giant land of ice and snow at the bottom of the world. Penguins love it here!",
    wow: "Almost all of Antarctica is covered in ice, some of it kilometres thick!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Antarctica_6400px_from_Blue_Marble.jpg/960px-Antarctica_6400px_from_Blue_Marble.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Antarctica_Oden_the_Ice_Breaker.jpg/960px-Antarctica_Oden_the_Ice_Breaker.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Antarctica_ice_shelf_system.jpg/960px-Antarctica_ice_shelf_system.jpg"
    ],
    video: "t3StWheKtq8",
  },
  {
    id: "asia",
    name: "Asia",
    place: "Continent",
    lat: 34.0,
    lng: 100.0,
    emoji: "🏯",
    color: "#e74c3c",
    kind: "continent",
    story:
      "Asia is the biggest continent of all. It has the tallest mountains, huge cities, thick forests, and more people than anywhere else.",
    wow: "More than half of all the people on Earth live in Asia!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Asia_satellite_orthographic.jpg/960px-Asia_satellite_orthographic.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Great_Wall_of_China_July_2006.JPG/960px-Great_Wall_of_China_July_2006.JPG",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Mount_Fuji_from_Lake_Kawaguchi.jpg/960px-Mount_Fuji_from_Lake_Kawaguchi.jpg"
    ],
    video: "1pNBDTNVhCw",
  },
  {
    id: "europe",
    name: "Europe",
    place: "Continent",
    lat: 50.0,
    lng: 10.0,
    emoji: "🏰",
    color: "#5b8def",
    kind: "continent",
    story:
      "Europe is a continent of many countries close together, with castles, old cities, mountains, and fairy-tale forests.",
    wow: "Even though it looks small on a globe, Europe has dozens of different countries!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Deforestation_central_Europe_-_Rodungen_Mitteleuropa.jpg/960px-Deforestation_central_Europe_-_Rodungen_Mitteleuropa.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Europe_satellite_orthographic.jpg/960px-Europe_satellite_orthographic.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Europ%C3%A4ische_Wasserscheiden.png/960px-Europ%C3%A4ische_Wasserscheiden.png"
    ],
    video: "RNx0akt3_XI",
  },
  {
    id: "northamerica",
    name: "North America",
    place: "Continent",
    lat: 45.0,
    lng: -100.0,
    emoji: "🍁",
    color: "#2a9d8f",
    kind: "continent",
    story:
      "North America stretches from icy northern lands down to sunny beaches. It has giant cities, big mountains, and wide plains.",
    wow: "It includes Canada, the United States, Mexico, and the countries of Central America and the Caribbean!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/e/ef/North_America_%281909%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/North_America_no_borders.png/960px-North_America_no_borders.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/North_America_satellite_orthographic.jpg/960px-North_America_satellite_orthographic.jpg"
    ],
    video: "XxK_hxZz9YQ",
  },
  {
    id: "southamerica",
    name: "South America",
    place: "Continent",
    lat: -15.0,
    lng: -60.0,
    emoji: "🦜",
    color: "#27ae60",
    kind: "continent",
    story:
      "South America is full of rainforests, long rivers, high mountains, and colourful birds. The Amazon jungle is here!",
    wow: "The Amazon River carries more water than any other river on Earth!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/e/e0/America_sattelite.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Amazon_Rainforest.jpg/960px-Amazon_Rainforest.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/South_America_satellite_orthographic.jpg/960px-South_America_satellite_orthographic.jpg"
    ],
    video: "Z4iwEMbal24",
  },
  {
    id: "oceania",
    name: "Oceania",
    place: "Continent region",
    lat: -25.0,
    lng: 135.0,
    emoji: "🦘",
    color: "#f4a261",
    kind: "continent",
    story:
      "Oceania is made of Australia, New Zealand, and lots of Pacific islands. Think kangaroos, beaches, and sparkling blue ocean.",
    wow: "There are thousands of islands in Oceania dotted across the Pacific!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Sydney_Opera_House_and_Harbour_Bridge_Dusk_%283%29_2019-06-21.jpg/960px-Sydney_Opera_House_and_Harbour_Bridge_Dusk_%283%29_2019-06-21.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/4/4f/Uluru_%28Ayers_Rock%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Anita_Bay_near_the_entrance_to_Milford_Sound.jpg/960px-Anita_Bay_near_the_entrance_to_Milford_Sound.jpg"
    ],
    video: "2_b-unDE77M",
  }
];


export const COUNTRIES = [
  {
    id: "usa",
    name: "United States",
    place: "North America",
    lat: 39.8283,
    lng: -98.5795,
    emoji: "🇺🇸",
    color: "#3c3b6e",
    kind: "country",
    continent: "northamerica",
    story:
      "A big country with 50 states, busy cities, huge parks, and coasts on two oceans. Its capital city is Washington, D.C.",
    wow: "It has both scorching deserts and snowy mountains in the same country!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Glacier_National_Park_-_HCP_-_October_23%2C_2022_-_001.jpg/960px-Glacier_National_Park_-_HCP_-_October_23%2C_2022_-_001.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Glacier_National_Park_-_HCP_-_October_23%2C_2022_-_002.jpg/960px-Glacier_National_Park_-_HCP_-_October_23%2C_2022_-_002.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Glacier_National_Park_-_HCP_-_October_23%2C_2022_-_003.jpg/960px-Glacier_National_Park_-_HCP_-_October_23%2C_2022_-_003.jpg"
    ],
    video: "BJXIjFq8fW8",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/5/5e/%22The_Star-Spangled_Banner%22_-_Choral_with_band_accompaniment_-_United_States_Army_Field_Band.oga",
  },
  {
    id: "canada",
    name: "Canada",
    place: "North America",
    lat: 56.1304,
    lng: -106.3468,
    emoji: "🇨🇦",
    color: "#ff0000",
    kind: "country",
    continent: "northamerica",
    story:
      "Canada is a huge northern country with lakes, forests, and friendly cities. Maple leaves and hockey are famous here.",
    wow: "Canada has more lakes than any other country in the world!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Banff_National_Park_%28AB%2C_Canada%29%2C_Lake_Louise_--_2022_--_2199.jpg/960px-Banff_National_Park_%28AB%2C_Canada%29%2C_Lake_Louise_--_2022_--_2199.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Castle_Mountain.jpg/960px-Castle_Mountain.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Cheops_Mountain_seen_the_Sir_Donald_Trail.jpg/960px-Cheops_Mountain_seen_the_Sir_Donald_Trail.jpg"
    ],
    video: "Qo7aTFHyhPE",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/c/cd/O_Canada_French_lyrics_1918.ogg",
  },
  {
    id: "mexico",
    name: "Mexico",
    place: "North America",
    lat: 23.6345,
    lng: -102.5528,
    emoji: "🇲🇽",
    color: "#006847",
    kind: "country",
    continent: "northamerica",
    story:
      "Mexico is full of colourful festivals, tasty food, deserts, jungles, and ancient stone cities.",
    wow: "Chocolate, corn, and chilli peppers first grew in this part of the world!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Teotihuacan_landscape_with_Pir%C3%A1mide_de_la_Luna.jpg/960px-Teotihuacan_landscape_with_Pir%C3%A1mide_de_la_Luna.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Amanecer_en_Huitzila%2C_M%C3%A9xico%2C_2013-10-10%2C_DD_01.JPG/960px-Amanecer_en_Huitzila%2C_M%C3%A9xico%2C_2013-10-10%2C_DD_01.JPG",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Chichen_Itza_3.jpg/960px-Chichen_Itza_3.jpg"
    ],
    video: "3fmGsWpPIlQ",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Himno_Nacional_Mexicano_en_lengua_Mixteca.oga",
  },
  {
    id: "brazil",
    name: "Brazil",
    place: "South America",
    lat: -14.235,
    lng: -51.9253,
    emoji: "🇧🇷",
    color: "#009c3b",
    kind: "country",
    continent: "southamerica",
    story:
      "Brazil is the biggest country in South America. It has the Amazon rainforest, lively cities, and long sandy beaches.",
    wow: "People in Brazil speak Portuguese — not Spanish like many nearby countries!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Amanhecer_no_Hercules_--.jpg/960px-Amanhecer_no_Hercules_--.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Athene_cunicularia_-near_Goiania%2C_Goias%2C_Brazil-8_edit.jpg/960px-Athene_cunicularia_-near_Goiania%2C_Goias%2C_Brazil-8_edit.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/7/79/Frans_Jansz._Post_-_Landscape_in_Brazil_with_Sugar_Plantation_-_KMSsp491_-_Statens_Museum_for_Kunst.jpg"
    ],
    video: "TaX0125QlUI",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/3/38/Hino_Nacional_Brasileiro_%28abreviado%29_-_Piano_e_Orquestra_Philharmonia.ogg",
  },
  {
    id: "argentina",
    name: "Argentina",
    place: "South America",
    lat: -38.4161,
    lng: -63.6167,
    emoji: "🇦🇷",
    color: "#74acdf",
    kind: "country",
    continent: "southamerica",
    story:
      "Argentina has grassy plains, big cities, and mountains at the tip of South America near icy Antarctica.",
    wow: "It is home to both jungles in the north and glaciers in the south!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Argentina_%284691434734%29.jpg/960px-Argentina_%284691434734%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Cordillera_Patagonia.jpg/960px-Cordillera_Patagonia.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Envisat_image_of_Patagonia_ESA217987.jpg/960px-Envisat_image_of_Patagonia_ESA217987.jpg"
    ],
    video: "1U0N4SGL46A",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/e/ec/Himno_Nacional_Argentino_short_instrumental.ogg",
  },
  {
    id: "peru",
    name: "Peru",
    place: "South America",
    lat: -9.19,
    lng: -75.0152,
    emoji: "🇵🇪",
    color: "#d91023",
    kind: "country",
    continent: "southamerica",
    story:
      "Peru has the Andes mountains, desert coast, rainforest, and ancient places high in the clouds.",
    wow: "Llamas and alpacas are everyday helpers in the mountains of Peru!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Laguna_de_Salinas%2C_Arequipa%2C_Per%C3%BA%2C_2015-08-02%2C_DD_16-19_PAN.JPG/960px-Laguna_de_Salinas%2C_Arequipa%2C_Per%C3%BA%2C_2015-08-02%2C_DD_16-19_PAN.JPG",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Oasis_de_Huacachina%2C_Ica%2C_Per%C3%BA%2C_2015-07-29%2C_DD_18.JPG/960px-Oasis_de_Huacachina%2C_Ica%2C_Per%C3%BA%2C_2015-07-29%2C_DD_18.JPG",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Oasis_de_Huacachina%2C_Ica%2C_Per%C3%BA%2C_2015-07-29%2C_DD_19-22_PAN.JPG/960px-Oasis_de_Huacachina%2C_Ica%2C_Per%C3%BA%2C_2015-07-29%2C_DD_19-22_PAN.JPG"
    ],
    video: "x0XCXGXGZMs",
    anthem: "4NIUhpCaUIU",
  },
  {
    id: "uk",
    name: "United Kingdom",
    place: "Europe",
    lat: 55.3781,
    lng: -3.436,
    emoji: "🇬🇧",
    color: "#012169",
    kind: "country",
    continent: "europe",
    story:
      "The United Kingdom is a group of countries on islands — England, Scotland, Wales, and Northern Ireland.",
    wow: "You can ride famous red buses and see a giant clock called Big Ben in London!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/-2021-03-15_Countryside_towards_Spa_Common%2C_Norfolk.jpg/960px--2021-03-15_Countryside_towards_Spa_Common%2C_Norfolk.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Countryside_landscape_-_geograph.org.uk_-_7164575.jpg/960px-Countryside_landscape_-_geograph.org.uk_-_7164575.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Mid_Devon_%2C_Countryside_Landscape_-_geograph.org.uk_-_3017047.jpg/960px-Mid_Devon_%2C_Countryside_Landscape_-_geograph.org.uk_-_3017047.jpg"
    ],
    video: "JXF0zyNnMhk",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/0/03/United_States_Navy_Band_-_God_Save_the_Queen.oga",
  },
  {
    id: "france",
    name: "France",
    place: "Europe",
    lat: 46.2276,
    lng: 2.2137,
    emoji: "🇫🇷",
    color: "#002395",
    kind: "country",
    continent: "europe",
    story:
      "France is known for the Eiffel Tower, delicious bakery treats, countryside villages, and sunny beaches.",
    wow: "France is the most visited country by travellers in the whole world!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Camille_Pissarro%2C_Landscape%2C_Ile-de-France%2C_1873%2C_NGA_164950.jpg/960px-Camille_Pissarro%2C_Landscape%2C_Ile-de-France%2C_1873%2C_NGA_164950.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Tour_Eiffel_Wikimedia_Commons.jpg/960px-Tour_Eiffel_Wikimedia_Commons.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Landscape_in_Peyriac-de-Mer%2C_february_2018_%2805%29.jpg/960px-Landscape_in_Peyriac-de-Mer%2C_february_2018_%2805%29.jpg"
    ],
    video: "XIkurVgGAaM",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/6/64/La_Marseillaise_%281907%29.oga",
  },
  {
    id: "italy",
    name: "Italy",
    place: "Europe",
    lat: 41.8719,
    lng: 12.5674,
    emoji: "🇮🇹",
    color: "#009246",
    kind: "country",
    continent: "europe",
    story:
      "Italy looks a bit like a boot on the map! It has pizza, pasta, old Roman buildings, and beautiful coastlines.",
    wow: "Italy has two tiny countries inside it: Vatican City and San Marino!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Bergwandeltocht_van_Peio_Paese_naar_Lago_Covel_%281%2C839_m%29_in_het_Nationaal_park_Stelvio_%28Italy%29_23.jpg/960px-Bergwandeltocht_van_Peio_Paese_naar_Lago_Covel_%281%2C839_m%29_in_het_Nationaal_park_Stelvio_%28Italy%29_23.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Hendrik_Voogd_-_Italian_landscape_with_Umbrella_Pines.jpg/960px-Hendrik_Voogd_-_Italian_landscape_with_Umbrella_Pines.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Marmolada%2C_Italy.jpg/960px-Marmolada%2C_Italy.jpg"
    ],
    video: "G_KMybIvv4c",
    anthem: "HNVwV0xWXdY",
  },
  {
    id: "germany",
    name: "Germany",
    place: "Europe",
    lat: 51.1657,
    lng: 10.4515,
    emoji: "🇩🇪",
    color: "#dd0000",
    kind: "country",
    continent: "europe",
    story:
      "Germany has fairy-tale castles, thick forests, busy cities, and lots of trains zooming between them.",
    wow: "Germany has more than 20,000 castles and castle ruins!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Schloss_Neuschwanstein_2013.jpg/960px-Schloss_Neuschwanstein_2013.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Brandenburger_Tor_abends.jpg/960px-Brandenburger_Tor_abends.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Burg_Eltz.jpg/960px-Burg_Eltz.jpg"
    ],
    video: "VXDFXNxmnO0",
    anthem: "Sj5bNbh0ZL0",
  },
  {
    id: "spain",
    name: "Spain",
    place: "Europe",
    lat: 40.4637,
    lng: -3.7492,
    emoji: "🇪🇸",
    color: "#aa151b",
    kind: "country",
    continent: "europe",
    story:
      "Spain is sunny and colourful, with beaches, mountains, festivals, and tasty food like paella and oranges.",
    wow: "Spain grows so many olives that it is one of the olive champions of the world!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Bunker_of_Albendin_in_Albendin%2C_Cordoba%2C_Spain_%282016%29_-_03.jpg/960px-Bunker_of_Albendin_in_Albendin%2C_Cordoba%2C_Spain_%282016%29_-_03.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Escultura_del_duende_del_Retiro.jpg/960px-Escultura_del_duende_del_Retiro.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Alhambra_Granada_Spain.jpg/960px-Alhambra_Granada_Spain.jpg"
    ],
    video: "KPGODwWDFXg",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Marcha_Real-Royal_March_by_US_Navy_Band.ogg",
  },
  {
    id: "greece",
    name: "Greece",
    place: "Europe",
    lat: 39.0742,
    lng: 21.8243,
    emoji: "🇬🇷",
    color: "#0d5eaf",
    kind: "country",
    continent: "europe",
    story:
      "Greece has blue seas, white island houses, and very old temples from long ago.",
    wow: "The Olympic Games began in ancient Greece thousands of years ago!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/20100919_Marmaritsa_beach_Maronia_Rhodope_Thrace_Greece_panorama.jpg/960px-20100919_Marmaritsa_beach_Maronia_Rhodope_Thrace_Greece_panorama.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Jean-Victor_Bertin_-_Landscape%2C_Site_of_Greece_%28Paysage%2C_Site_de_la_Gr%C3%A8ce%29_-_Google_Art_Project.jpg/960px-Jean-Victor_Bertin_-_Landscape%2C_Site_of_Greece_%28Paysage%2C_Site_de_la_Gr%C3%A8ce%29_-_Google_Art_Project.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Landscape_Eretria_Euboea_Greece.jpg/960px-Landscape_Eretria_Euboea_Greece.jpg"
    ],
    video: "RchSJSJAbc0",
    anthem: "y5psd0qpjls",
  },
  {
    id: "egypt",
    name: "Egypt",
    place: "Africa",
    lat: 26.8206,
    lng: 30.8025,
    emoji: "🇪🇬",
    color: "#ce1126",
    kind: "country",
    continent: "africa",
    story:
      "Egypt is a desert country with the long River Nile, giant pyramids, and stories from ancient times.",
    wow: "Almost everyone in Egypt lives near the Nile because the desert is so dry!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/EGYPT._-_Landscape_%28n.d.%29_-_front_-_TIMEA.jpg/960px-EGYPT._-_Landscape_%28n.d.%29_-_front_-_TIMEA.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/EGYPT._-_Landscape_with_the_Pyramids_of_Giza_%28n.d.%29_-_front_-_TIMEA.jpg/960px-EGYPT._-_Landscape_with_the_Pyramids_of_Giza_%28n.d.%29_-_front_-_TIMEA.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/All_Gizah_Pyramids.jpg/960px-All_Gizah_Pyramids.jpg"
    ],
    video: "tsMWYzvsqHk",
    anthem: "qsjuPQ6MVNU",
  },
  {
    id: "kenya",
    name: "Kenya",
    place: "Africa",
    lat: -0.0236,
    lng: 37.9062,
    emoji: "🇰🇪",
    color: "#bb0000",
    kind: "country",
    continent: "africa",
    story:
      "Kenya is famous for safaris — wide grasslands where you can see elephants, lions, zebras, and giraffes.",
    wow: "Millions of wildebeest travel across Kenya every year in a giant animal parade!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Fairmont_Mount_Kenya_Safari_Club_Resort.jpg/960px-Fairmont_Mount_Kenya_Safari_Club_Resort.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Kenya%2C_Safari_%2832244333948%29.jpg/960px-Kenya%2C_Safari_%2832244333948%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Kenya%2C_Safari_%2844299246530%29.jpg/960px-Kenya%2C_Safari_%2844299246530%29.jpg"
    ],
    video: "Vj0FFQ9hkYM",
    anthem: "3onl8WHLyF0",
  },
  {
    id: "southafrica",
    name: "South Africa",
    place: "Africa",
    lat: -30.5595,
    lng: 22.9375,
    emoji: "🇿🇦",
    color: "#007a4d",
    kind: "country",
    continent: "africa",
    story:
      "South Africa is at the tip of Africa, with beaches, wildlife parks, mountains, and big cities.",
    wow: "It has three capital cities — one for laws, one for government, and one for courts!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Kalahari_landscape%2C_Kalahari%2C_Northern_Cape%2C_South_Africa_%2820544760631%29.jpg/960px-Kalahari_landscape%2C_Kalahari%2C_Northern_Cape%2C_South_Africa_%2820544760631%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Karoo_Landscape%2C_Nqweba%2C_Eastern_Cape%2C_South_Africa_%2820324198338%29.jpg/960px-Karoo_Landscape%2C_Nqweba%2C_Eastern_Cape%2C_South_Africa_%2820324198338%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Landscape%2C_Vioolsdrift%2C_Richtersveld%2C_Northern_Cape%2C_South_Africa_%2819917794884%29.jpg/960px-Landscape%2C_Vioolsdrift%2C_Richtersveld%2C_Northern_Cape%2C_South_Africa_%2819917794884%29.jpg"
    ],
    video: "GYgnxfgf16Q",
    anthem: "NBKjWRjwMkY",
  },
  {
    id: "morocco",
    name: "Morocco",
    place: "Africa",
    lat: 31.7917,
    lng: -7.0926,
    emoji: "🇲🇦",
    color: "#c1272d",
    kind: "country",
    continent: "africa",
    story:
      "Morocco has busy markets, blue towns, sandy deserts, and mountains not far from the sea.",
    wow: "You can ride a camel in the Sahara Desert and see the Atlantic Ocean in the same country!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Arhbalou_High_Atlas_Al_Haouz_Morocco_Oct25_A7CR_08381.jpg/960px-Arhbalou_High_Atlas_Al_Haouz_Morocco_Oct25_A7CR_08381.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Camel_Tour_on_Erg_Chebbi_riding_across_the_dunes.jpg/960px-Camel_Tour_on_Erg_Chebbi_riding_across_the_dunes.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Djebel_Ayachi%2C_Eastern_High_Atlas%2C_Morocco.jpg/960px-Djebel_Ayachi%2C_Eastern_High_Atlas%2C_Morocco.jpg"
    ],
    video: "9iqBeJnsq8U",
    anthem: "3sSp5PI-xWQ",
  },
  {
    id: "china",
    name: "China",
    place: "Asia",
    lat: 35.8617,
    lng: 104.1954,
    emoji: "🇨🇳",
    color: "#de2910",
    kind: "country",
    continent: "asia",
    story:
      "China is a huge Asian country with giant cities, long rivers, mountains, and the Great Wall.",
    wow: "More people live in China than in almost any other country on Earth!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/1996_-261-26_Guilin_%28Li_River%29_%285068520197%29.jpg/960px-1996_-261-26_Guilin_%28Li_River%29_%285068520197%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/1996_-263-28_Guilin_%28Li_River%29_%285069135168%29.jpg/960px-1996_-263-28_Guilin_%28Li_River%29_%285069135168%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/1996_-264-4_Guilin_%28Li_River%29_%2847515605431%29.jpg/960px-1996_-264-4_Guilin_%28Li_River%29_%2847515605431%29.jpg"
    ],
    video: "q7JK5Vxf_VQ",
    anthem: "IeMFXiEq_ow",
  },
  {
    id: "japan",
    name: "Japan",
    place: "Asia",
    lat: 36.2048,
    lng: 138.2529,
    emoji: "🇯🇵",
    color: "#bc002d",
    kind: "country",
    continent: "asia",
    story:
      "Japan is a country of islands with cherry blossoms, fast trains, busy cities, and beautiful Mount Fuji.",
    wow: "Japan’s bullet trains can go faster than many race cars!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Mount_Fuji_from_Lake_Kawaguchi.jpg/960px-Mount_Fuji_from_Lake_Kawaguchi.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Tokyo_Tower_and_around_Skyscrapers.jpg/960px-Tokyo_Tower_and_around_Skyscrapers.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Torii_of_Itsukushima_Shrine.jpg/960px-Torii_of_Itsukushima_Shrine.jpg"
    ],
    video: "QEC3MrWgnMU",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/8/88/Kimigayo_vocal_1930.ogg",
  },
  {
    id: "india",
    name: "India",
    place: "Asia",
    lat: 20.5937,
    lng: 78.9629,
    emoji: "🇮🇳",
    color: "#ff9933",
    kind: "country",
    continent: "asia",
    story:
      "India is colourful and busy, with festivals, spicy food, tigers, and the sparkling Taj Mahal.",
    wow: "India has hundreds of languages spoken across the country!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Gangabal_Lake%2C_India%2C_by_George_Strahan.jpg/960px-Gangabal_Lake%2C_India%2C_by_George_Strahan.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Hampi%2C_India%2C_Rocky_landscape_of_Hampi%2C_Granite_rocks_of_Matanga_Hill.jpg/960px-Hampi%2C_India%2C_Rocky_landscape_of_Hampi%2C_Granite_rocks_of_Matanga_Hill.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Horses_grazing_at_Trunkol_meadow%2C_Jammu_and_Kashmir%2C_India_%28crop%29.jpg/960px-Horses_grazing_at_Trunkol_meadow%2C_Jammu_and_Kashmir%2C_India_%28crop%29.jpg"
    ],
    video: "6J6UpxMxG_8",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Jana_Gana_Mana.ogg",
  },
  {
    id: "indonesia",
    name: "Indonesia",
    place: "Asia",
    lat: -0.7893,
    lng: 113.9213,
    emoji: "🇮🇩",
    color: "#ce1126",
    kind: "country",
    continent: "asia",
    story:
      "Indonesia is made of thousands of islands with volcanoes, rainforests, and warm blue seas.",
    wow: "It has more volcanoes than any other country!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Bali%2C_Extinct_caldera_slopes%2C_Forest%2C_East_Bali%2C_Indonesia.jpg/960px-Bali%2C_Extinct_caldera_slopes%2C_Forest%2C_East_Bali%2C_Indonesia.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Bali%2C_Forest%2C_Trees%2C_East_Bali%2C_Indonesia.jpg/960px-Bali%2C_Forest%2C_Trees%2C_East_Bali%2C_Indonesia.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Bali%2C_Mount_Seraya%2C_Forest%2C_East_Bali%2C_Indonesia.jpg/960px-Bali%2C_Mount_Seraya%2C_Forest%2C_East_Bali%2C_Indonesia.jpg"
    ],
    video: "FsXc3FcWi3g",
    anthem: "Rc2dG7uMlhA",
  },
  {
    id: "thailand",
    name: "Thailand",
    place: "Asia",
    lat: 15.87,
    lng: 100.9925,
    emoji: "🇹🇭",
    color: "#a51931",
    kind: "country",
    continent: "asia",
    story:
      "Thailand has golden temples, tropical beaches, elephants, and friendly smiling cities.",
    wow: "Thai food is famous for mixing sweet, sour, salty, and spicy in one bite!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Karst_landscape_of_Cheow_Lan_Lake%2C_Thailand.jpg/960px-Karst_landscape_of_Cheow_Lan_Lake%2C_Thailand.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Koh_Mak_%28island%29%2C_Thailand%2C_Solitary_tree_in_lagoon.jpg/960px-Koh_Mak_%28island%29%2C_Thailand%2C_Solitary_tree_in_lagoon.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Koh_Mak_%28island%29%2C_Thailand%2C_Solitary_tree_in_tropical_lagoon.jpg/960px-Koh_Mak_%28island%29%2C_Thailand%2C_Solitary_tree_in_tropical_lagoon.jpg"
    ],
    video: "84j7dvY-6Uw",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/2/24/Phleng_Chat_Thai_%28Intro%2BInstrumental%29_-_Rabbit_Gramophone_record.ogg",
  },
  {
    id: "russia",
    name: "Russia",
    place: "Europe & Asia",
    lat: 61.524,
    lng: 105.3188,
    emoji: "🇷🇺",
    color: "#0039a6",
    kind: "country",
    continent: "asia",
    story:
      "Russia is the biggest country on Earth by land. It stretches across two continents: Europe and Asia.",
    wow: "Crossing Russia on the train can take more than a week!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/G.Quarenghi_-_Views_of_Moscow_and_its_Environs_-_Sobornaya_Square_at_the_Moscow_Kremlin_-_1797_-_color_balanced.jpg/960px-G.Quarenghi_-_Views_of_Moscow_and_its_Environs_-_Sobornaya_Square_at_the_Moscow_Kremlin_-_1797_-_color_balanced.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Kazan_Cathedral_in_Moscow_-_onion_dome%2C_tholobate_and_kokoshniks.jpg/960px-Kazan_Cathedral_in_Moscow_-_onion_dome%2C_tholobate_and_kokoshniks.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Moscow%2C_Dushkin%27s_Tower.jpg/960px-Moscow%2C_Dushkin%27s_Tower.jpg"
    ],
    video: "eIHQKQxKKhY",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Gimn_rf_t1.ogg",
  },
  {
    id: "australia",
    name: "Australia",
    place: "Oceania",
    lat: -25.2744,
    lng: 133.7751,
    emoji: "🇦🇺",
    color: "#00008b",
    kind: "country",
    continent: "oceania",
    story:
      "Australia is both a country and a huge island continent, with kangaroos, beaches, and the Outback desert.",
    wow: "Many of Australia’s animals, like kangaroos and koalas, live nowhere else in the wild!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Australian_Outback.jpg/960px-Australian_Outback.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Australian_Outback_-_2.jpg/960px-Australian_Outback_-_2.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Mount_Conner%2C_August_2003.jpg/960px-Mount_Conner%2C_August_2003.jpg"
    ],
    video: "zmon5Tv6bYU",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/0/06/U.S._Navy_Band%2C_Advance_Australia_Fair_%28abridged%29.oga",
  },
  {
    id: "newzealand",
    name: "New Zealand",
    place: "Oceania",
    lat: -40.9006,
    lng: 174.886,
    emoji: "🇳🇿",
    color: "#00247d",
    kind: "country",
    continent: "oceania",
    story:
      "New Zealand has two main islands full of mountains, beaches, sheep, and friendly towns — including Auckland and Wellington.",
    wow: "There are many more sheep than people in New Zealand!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Ahuriri_River_before_sunrise%2C_Canterbury%2C_New_Zealand.jpg/960px-Ahuriri_River_before_sunrise%2C_Canterbury%2C_New_Zealand.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Angelus_Hut_in_the_winter%2C_Nelson_Lakes_National_Park%2C_New_Zealand.jpg/960px-Angelus_Hut_in_the_winter%2C_Nelson_Lakes_National_Park%2C_New_Zealand.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Camp_Saddle%2C_Craigieburn_Range%2C_New_Zealand_14.jpg/960px-Camp_Saddle%2C_Craigieburn_Range%2C_New_Zealand_14.jpg"
    ],
    video: "FtZaaKFi7RM",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/d/d6/God_Defend_New_Zealand_instrumental.ogg",
  },
  {
    id: "poland",
    name: "Poland",
    place: "Europe",
    lat: 51.9194,
    lng: 19.1451,
    emoji: "🇵🇱",
    color: "#dc143c",
    kind: "country",
    continent: "europe",
    story:
      "Poland is a country in central Europe with old cities, deep forests, and tasty pierogi dumplings.",
    wow: "Poland’s national anthem is a cheerful marching song from long ago!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Wawel_Castle%2C_Krakow%2C_Poland.jpg/960px-Wawel_Castle%2C_Krakow%2C_Poland.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Warsaw_Old_Town_Market_Square_%282%29.jpg/960px-Warsaw_Old_Town_Market_Square_%282%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Bialowieza_National_Park_in_Poland.jpg/960px-Bialowieza_National_Park_in_Poland.jpg"
    ],
    video: "RNx0akt3_XI",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Mazurek_Dabrowskiego.ogg",
  },
  {
    id: "sweden",
    name: "Sweden",
    place: "Europe",
    lat: 60.1282,
    lng: 18.6435,
    emoji: "🇸🇪",
    color: "#006aa7",
    kind: "country",
    continent: "europe",
    story:
      "Sweden is a northern country with lakes, forests, and long bright summers. Kids there love cinnamon buns!",
    wow: "In far-north Sweden, the summer sun barely sets — it can stay light almost all night!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Stockholm_panorama_2018.jpg/960px-Stockholm_panorama_2018.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Kiruna_midnight_sun.jpg/960px-Kiruna_midnight_sun.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Abisko_National_Park_Sweden.jpg/960px-Abisko_National_Park_Sweden.jpg"
    ],
    video: "RNx0akt3_XI",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/a/a2/Du_gamla%2C_du_fria.ogg",
  },
  {
    id: "portugal",
    name: "Portugal",
    place: "Europe",
    lat: 39.3999,
    lng: -8.2245,
    emoji: "🇵🇹",
    color: "#006600",
    kind: "country",
    continent: "europe",
    story:
      "Portugal sits on Europe’s west coast with sunny beaches, tiled cities, and delicious pastries.",
    wow: "Portuguese sailors once explored oceans all around the world!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Lisbon_Portugal_%28Unsplash%29.jpg/960px-Lisbon_Portugal_%28Unsplash%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Porto_Portugal_Ribeira.jpg/960px-Porto_Portugal_Ribeira.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Algarve_beach_Portugal.jpg/960px-Algarve_beach_Portugal.jpg"
    ],
    video: "RNx0akt3_XI",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/5/58/A_Portuguesa.ogg",
  },
  {
    id: "southkorea",
    name: "South Korea",
    place: "Asia",
    lat: 35.9078,
    lng: 127.7669,
    emoji: "🇰🇷",
    color: "#0047a0",
    kind: "country",
    continent: "asia",
    story:
      "South Korea is a country of busy cities, green mountains, and amazing technology — plus tasty food like kimchi!",
    wow: "Seoul is one of the biggest cities on Earth, with millions of people!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Gyeongbokgung-Palace.jpg/960px-Gyeongbokgung-Palace.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Seoul_cityscape.jpg/960px-Seoul_cityscape.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Jeju_Island_Korea.jpg/960px-Jeju_Island_Korea.jpg"
    ],
    video: "1pNBDTNVhCw",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/5/5e/National_Anthem_of_Republic_of_Korea_2018_Orchestral_(1_Verse_Version).ogg",
  },
  {
    id: "chile",
    name: "Chile",
    place: "South America",
    lat: -35.6751,
    lng: -71.543,
    emoji: "🇨🇱",
    color: "#0039a6",
    kind: "country",
    continent: "southamerica",
    story:
      "Chile is a long skinny country along South America’s Pacific coast, with deserts in the north and icy lands in the south.",
    wow: "Chile is so long it can take days to drive from top to bottom!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Torres_del_Paine_%28Chile%29.jpg/960px-Torres_del_Paine_%28Chile%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Atacama_Desert_Chile.jpg/960px-Atacama_Desert_Chile.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Santiago_de_Chile.jpg/960px-Santiago_de_Chile.jpg"
    ],
    video: "Z4iwEMbal24",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/b/b5/Himno_Nacional_de_Chile.ogg",
  },
  {
    id: "colombia",
    name: "Colombia",
    place: "South America",
    lat: 4.5709,
    lng: -74.2973,
    emoji: "🇨🇴",
    color: "#fcd116",
    kind: "country",
    continent: "southamerica",
    story:
      "Colombia has jungles, coffee hills, Caribbean beaches, and colourful cities high in the Andes.",
    wow: "More kinds of birds live in Colombia than in almost any other country!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Cartagena%2C_Colombia.jpg/960px-Cartagena%2C_Colombia.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Cocora_valley_Colombia.jpg/960px-Cocora_valley_Colombia.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Bogota_Colombia.jpg/960px-Bogota_Colombia.jpg"
    ],
    video: "Z4iwEMbal24",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Himno_Nacional_de_la_Republica_de_Colombia.ogg",
  },
  {
    id: "netherlands",
    name: "Netherlands",
    place: "Europe",
    lat: 52.1326,
    lng: 5.2913,
    emoji: "🇳🇱",
    color: "#ae1c28",
    kind: "country",
    continent: "europe",
    story:
      "The Netherlands is a flat country of canals, bikes, windmills, and bright tulip fields.",
    wow: "A big part of the land was once under the sea — people pumped the water out!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Amsterdam_canals.jpg/960px-Amsterdam_canals.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Keukenhof.jpg/960px-Keukenhof.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Kinderdijk_molens.jpg/960px-Kinderdijk_molens.jpg"
    ],
    video: "XIkurVgGAaM",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/2/26/Wilhelmus_vocal.ogg",
  },
  {
    id: "norway",
    name: "Norway",
    place: "Europe",
    lat: 60.472,
    lng: 8.4689,
    emoji: "🇳🇴",
    color: "#ba0c2f",
    kind: "country",
    continent: "europe",
    story:
      "Norway has deep blue fjords, snowy mountains, and villages tucked along the coast.",
    wow: "In winter you can see the northern lights dance across Norway’s night sky!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Geirangerfjord_from_Flydalsjuvet.jpg/960px-Geirangerfjord_from_Flydalsjuvet.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Preikestolen_2010.jpg/960px-Preikestolen_2010.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Aurora_Borealis_and_tent.jpg/960px-Aurora_Borealis_and_tent.jpg"
    ],
    video: "RNx0akt3_XI",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Ja_vi_elsker.ogg",
  },
  {
    id: "ireland",
    name: "Ireland",
    place: "Europe",
    lat: 53.1424,
    lng: -7.6921,
    emoji: "🇮🇪",
    color: "#169b62",
    kind: "country",
    continent: "europe",
    story:
      "Ireland is a green island of cliffs, castles, music, and friendly towns.",
    wow: "People sometimes call it the Emerald Isle because it looks so green from above!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Cliffs_of_Moher%2C_Ireland.jpg/960px-Cliffs_of_Moher%2C_Ireland.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Giant%27s_Causeway_%28PPL1-Corrected%29.jpg/960px-Giant%27s_Causeway_%28PPL1-Corrected%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Dublin_Ireland.jpg/960px-Dublin_Ireland.jpg"
    ],
    video: "JXF0zyNnMhk",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Amhran_na_bhFiann.ogg",
  },
  {
    id: "switzerland",
    name: "Switzerland",
    place: "Europe",
    lat: 46.8182,
    lng: 8.2275,
    emoji: "🇨🇭",
    color: "#d52b1e",
    kind: "country",
    continent: "europe",
    story:
      "Switzerland is a mountain country with tall Alps, chocolate, cheese, and quiet lakes.",
    wow: "Switzerland has four national languages — kids may hear German, French, Italian, or Romansh!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Matterhorn_from_Domh%C3%BCtte_-_2.jpg/960px-Matterhorn_from_Domh%C3%BCtte_-_2.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Lake_Lucerne.jpg/960px-Lake_Lucerne.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Jungfraujoch.jpg/960px-Jungfraujoch.jpg"
    ],
    video: "VXDFXNxmnO0",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/3/3a/Swiss_Psalm.ogg",
  },
  {
    id: "turkey",
    name: "Turkey",
    place: "Europe & Asia",
    lat: 38.9637,
    lng: 35.2433,
    emoji: "🇹🇷",
    color: "#e30a17",
    kind: "country",
    continent: "asia",
    story:
      "Turkey bridges Europe and Asia. It has busy markets, hot-air balloons over fairy chimneys, and seas on three sides.",
    wow: "Istanbul is a huge city that sits on two continents at once!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Hagia_Sophia_Mars_2013.jpg/960px-Hagia_Sophia_Mars_2013.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Cappadocia_balloon_flight.jpg/960px-Cappadocia_balloon_flight.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Pamukkale_Turkey.jpg/960px-Pamukkale_Turkey.jpg"
    ],
    video: "RchSJSJAbc0",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Istiklal_Marsi.ogg",
  },
  {
    id: "iceland",
    name: "Iceland",
    place: "Europe",
    lat: 64.9631,
    lng: -19.0208,
    emoji: "🇮🇸",
    color: "#02529c",
    kind: "country",
    continent: "europe",
    weather: "snow",
    story:
      "Iceland is a volcanic island with geysers, waterfalls, glaciers, and black-sand beaches.",
    wow: "In Iceland you can stand between two tectonic plates pulling apart!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Gullfoss_from_top.jpg/960px-Gullfoss_from_top.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Strokkur_geyser.jpg/960px-Strokkur_geyser.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Reynisfjara.jpg/960px-Reynisfjara.jpg"
    ],
    video: "RNx0akt3_XI",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/6/6b/Lofs%C3%B6ngur.ogg",
  },
  {
    id: "finland",
    name: "Finland",
    place: "Europe",
    lat: 61.9241,
    lng: 25.7482,
    emoji: "🇫🇮",
    color: "#003580",
    kind: "country",
    continent: "europe",
    story:
      "Finland is a northern land of thousands of lakes, thick forests, and cosy saunas.",
    wow: "Finland has more saunas than cars in some towns — steaming is a national hobby!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Helsinki_Cathedral_in_July_2004.jpg/960px-Helsinki_Cathedral_in_July_2004.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Northern_lights_in_Lapland.jpg/960px-Northern_lights_in_Lapland.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Lake_Saimaa.jpg/960px-Lake_Saimaa.jpg"
    ],
    video: "RNx0akt3_XI",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/5/55/Maamme_%28vocal%29.ogg",
  },
  {
    id: "nigeria",
    name: "Nigeria",
    place: "Africa",
    lat: 9.082,
    lng: 8.6753,
    emoji: "🇳🇬",
    color: "#008751",
    kind: "country",
    continent: "africa",
    story:
      "Nigeria is a lively West African country with big cities, music, markets, and many languages.",
    wow: "More people live in Nigeria than in any other country in Africa!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Lagos_Nigeria.jpg/960px-Lagos_Nigeria.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Yankari_National_Park.jpg/960px-Yankari_National_Park.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Olumo_Rock.jpg/960px-Olumo_Rock.jpg"
    ],
    video: "Vj0FFQ9hkYM",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Nigeria_National_Anthem.ogg",
  },
  {
    id: "ethiopia",
    name: "Ethiopia",
    place: "Africa",
    lat: 9.145,
    lng: 40.4897,
    emoji: "🇪🇹",
    color: "#078930",
    kind: "country",
    continent: "africa",
    story:
      "Ethiopia has high plateaus, rock-hewn churches, and ancient stories. Coffee plants first grew here!",
    wow: "Ethiopia uses its own calendar and its own clock hours — time feels different!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Lalibela_Bete_Giyorgis.jpg/960px-Lalibela_Bete_Giyorgis.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Simien_Mountains.jpg/960px-Simien_Mountains.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Addis_Ababa.jpg/960px-Addis_Ababa.jpg"
    ],
    video: "Vj0FFQ9hkYM",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/9/9e/Ethiopia_National_Anthem.ogg",
  },
  {
    id: "ghana",
    name: "Ghana",
    place: "Africa",
    lat: 7.9465,
    lng: -1.0232,
    emoji: "🇬🇭",
    color: "#006b3f",
    kind: "country",
    continent: "africa",
    story:
      "Ghana is on Africa’s west coast, with beaches, cocoa farms, and friendly festivals.",
    wow: "A lot of the world’s chocolate starts as cocoa beans grown in Ghana!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Cape_Coast_Castle.jpg/960px-Cape_Coast_Castle.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Kakum_National_Park.jpg/960px-Kakum_National_Park.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Accra_Ghana.jpg/960px-Accra_Ghana.jpg"
    ],
    video: "Vj0FFQ9hkYM",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/1/1a/God_Bless_Our_Homeland_Ghana.ogg",
  },
  {
    id: "tanzania",
    name: "Tanzania",
    place: "Africa",
    lat: -6.369,
    lng: 34.8888,
    emoji: "🇹🇿",
    color: "#1eb53a",
    kind: "country",
    continent: "africa",
    story:
      "Tanzania has Mount Kilimanjaro, huge wildlife parks, and the spice island of Zanzibar.",
    wow: "Kilimanjaro is Africa’s tallest mountain — with snow on top near the equator!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Mount_Kilimanjaro.jpg/960px-Mount_Kilimanjaro.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Serengeti_sunset.jpg/960px-Serengeti_sunset.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Zanzibar_beach.jpg/960px-Zanzibar_beach.jpg"
    ],
    video: "Vj0FFQ9hkYM",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Mungu_ibariki_Afrika.ogg",
  },
  {
    id: "vietnam",
    name: "Vietnam",
    place: "Asia",
    lat: 14.0583,
    lng: 108.2772,
    emoji: "🇻🇳",
    color: "#da251d",
    kind: "country",
    continent: "asia",
    story:
      "Vietnam is a long skinny country with rice paddies, busy cities, and limestone islands in blue bays.",
    wow: "Halong Bay has thousands of rocky islands rising straight out of the sea!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Ha_Long_Bay.jpg/960px-Ha_Long_Bay.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Hoi_An_Vietnam.jpg/960px-Hoi_An_Vietnam.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Terraced_rice_fields_Vietnam.jpg/960px-Terraced_rice_fields_Vietnam.jpg"
    ],
    video: "84j7dvY-6Uw",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Tien_Quan_Ca.ogg",
  },
  {
    id: "philippines",
    name: "Philippines",
    place: "Asia",
    lat: 12.8797,
    lng: 121.774,
    emoji: "🇵🇭",
    color: "#0038a8",
    kind: "country",
    continent: "asia",
    story:
      "The Philippines is made of more than seven thousand islands with beaches, volcanoes, and cheerful festivals.",
    wow: "You could visit a new island every day for years and still not see them all!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Chocolate_Hills.jpg/960px-Chocolate_Hills.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Palawan_island.jpg/960px-Palawan_island.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Mayon_Volcano.jpg/960px-Mayon_Volcano.jpg"
    ],
    video: "FsXc3FcWi3g",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Lupang_Hinirang.ogg",
  },
  {
    id: "saudiarabia",
    name: "Saudi Arabia",
    place: "Asia",
    lat: 23.8859,
    lng: 45.0792,
    emoji: "🇸🇦",
    color: "#006c35",
    kind: "country",
    continent: "asia",
    story:
      "Saudi Arabia is a large desert country on the Arabian Peninsula, with huge dunes and modern cities.",
    wow: "Some sand dunes here are taller than skyscrapers!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Empty_Quarter_Saudi_Arabia.jpg/960px-Empty_Quarter_Saudi_Arabia.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Riyadh_Saudi_Arabia.jpg/960px-Riyadh_Saudi_Arabia.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/AlUla_Saudi_Arabia.jpg/960px-AlUla_Saudi_Arabia.jpg"
    ],
    video: "q7JK5Vxf_VQ",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Saudi_Arabia_National_Anthem.ogg",
  },
  {
    id: "singapore",
    name: "Singapore",
    place: "Asia",
    lat: 1.3521,
    lng: 103.8198,
    emoji: "🇸🇬",
    color: "#ed2939",
    kind: "country",
    continent: "asia",
    story:
      "Singapore is a tiny island city-state with shiny towers, gardens, and ships from all over the world.",
    wow: "Even though it is small, Singapore is one of the world’s busiest ports!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Marina_Bay_Sands.jpg/960px-Marina_Bay_Sands.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Gardens_by_the_Bay.jpg/960px-Gardens_by_the_Bay.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Merlion_Singapore.jpg/960px-Merlion_Singapore.jpg"
    ],
    video: "84j7dvY-6Uw",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/6/6b/Majulah_Singapura.ogg",
  },
  {
    id: "costarica",
    name: "Costa Rica",
    place: "North America",
    lat: 9.7489,
    lng: -83.7534,
    emoji: "🇨🇷",
    color: "#00247d",
    kind: "country",
    continent: "northamerica",
    story:
      "Costa Rica is a green Central American country with rainforests, volcanoes, and two oceans.",
    wow: "People say “Pura vida!” — it means pure life, and you’ll hear it everywhere!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Arenal_Volcano.jpg/960px-Arenal_Volcano.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Manuel_Antonio_National_Park.jpg/960px-Manuel_Antonio_National_Park.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Monteverde_Costa_Rica.jpg/960px-Monteverde_Costa_Rica.jpg"
    ],
    video: "3fmGsWpPIlQ",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Himno_Nacional_de_Costa_Rica.ogg",
  },
  {
    id: "cuba",
    name: "Cuba",
    place: "North America",
    lat: 21.5218,
    lng: -77.7812,
    emoji: "🇨🇺",
    color: "#002a8f",
    kind: "country",
    continent: "northamerica",
    story:
      "Cuba is a Caribbean island with colourful cars, music in the streets, and warm turquoise water.",
    wow: "Cuba is the biggest island in the Caribbean Sea!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Havana_Cuba.jpg/960px-Havana_Cuba.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Vinales_Valley_Cuba.jpg/960px-Vinales_Valley_Cuba.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Trinidad_Cuba.jpg/960px-Trinidad_Cuba.jpg"
    ],
    video: "3fmGsWpPIlQ",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/2/2a/La_Bayamesa.ogg",
  },
  {
    id: "fiji",
    name: "Fiji",
    place: "Oceania",
    lat: -17.7134,
    lng: 178.065,
    emoji: "🇫🇯",
    color: "#68bfe5",
    kind: "country",
    continent: "oceania",
    story:
      "Fiji is a Pacific island country with coral reefs, coconut palms, and smiling villages.",
    wow: "Fiji has hundreds of islands — some you can only reach by boat!",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Fiji_beach.jpg/960px-Fiji_beach.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Fiji_islands.jpg/960px-Fiji_islands.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Suva_Fiji.jpg/960px-Suva_Fiji.jpg"
    ],
    video: "FtZaaKFi7RM",
    anthem: "https://upload.wikimedia.org/wikipedia/commons/7/7b/God_Bless_Fiji.ogg",
  }
];
